server:
    port: 8084
spring:
    application:
        name: admin-service
    datasource:
        password: ${DB_PASSWORD:Manhcuong281207@}
        url: ${DB_URL:jdbc:postgresql://localhost:5432/mc_music_db?currentSchema=mc_music_admin_schema}
        username: ${DB_USERNAME:postgres}
    jpa:
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
jwt:
    secret: ${JWT_SECRET:superSecretKeyForAdminServiceThatIsAtLeast32CharsLong}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}
